# Copyright 2020 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/kernel/migrated_targets.gni")

zx_library("page_cache") {
  sources = [ "page_cache.cc" ]
  deps = [
    "tests",
    "//mk/lib/counters",
    "//mk/lib/crypto",
  ]
  public_deps = [ "//mk/lib/ktl:headers" ]
}
