# Copyright 2023 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/kernel/migrated_targets.gni")

zx_library("thread_sampler") {
  sources = [
    "buffer_writer.cc",
    "per_cpu_state.cc",
    "thread_sampler.cc",
  ]
  deps = [
    "//mk/lib/boot-options",
    "//mk/lib/fit",
    "//mk/lib/fxt",
    "//mk/lib/init",
  ]
  public_deps = [
    "//mk/lib/fxt:headers",
    "//mk/object:headers",
  ]
}
