# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/kernel/zx_library.gni")
import("//build/toolchain/toolchain_environment.gni")

zx_library("pc") {
  sources = [
    "acpi.cc",
    "cmos_bootbyte.cc",
    "console.cc",
    "dev-init.cc",
    "efi_expected.cc",
    "hpet.cc",
    "interrupts.cc",
    "keyboard.cc",
    "memory.cc",
    "pic.cc",
    "platform.cc",
    "power.cc",
    "smbios.cc",
    "timer.cc",
    "uart.cc",
  ]

  deps = [
    #":tests",
    "//mk/arch/x86:headers",
    "//mk/dev/hw_rng/intel_rng",
    "//mk/dev/interrupt",
    "//mk/dev/pcie",
    "//mk/lib/acpi_lite",
    "//mk/lib/arch",
    "//mk/lib/boot-options",
    "//mk/lib/cbuf",
    "//mk/lib/console",
    "//mk/lib/counters",
    "//mk/lib/debuglog",
    "//mk/lib/efi",
    "//mk/lib/fbl",
    "//mk/lib/fixed_point",
    "//mk/lib/init",
    #"//mk/lib/jtrace:headers",
    "//mk/lib/ktl",
    "//mk/lib/lockdep",
    "//mk/lib/pow2_range_allocator",
    "//mk/lib/topology",
    "//mk/lib/unittest",
    "//mk/lib/zbi-format",
    "//mk/phys:handoff",
    "//mk/phys/lib/memalloc:range",
    "//mk/platform:headers",
    "//mk/third_party/ulib/cksum",
    "//mk/ulib/explicit-memory",
    "//mk/ulib/lazy_init",
    "//mk/ulib/ram-crashlog",
    "//mk/ulib/smbios",
    "//mk/ulib/uart",
    "//src/lib/zbitl",
  ]
  public_deps = [
    # <platform/pc/smbios.h> has #include <lib/smbios/smbios.h>.
    "//mk/ulib/smbios:headers",

    # <ktl/optional.h> in uart.h.
    "//mk/lib/ktl:headers",
  ]

  if (toolchain_environment == "kernel") {
    public_deps += [
      # <platform/pc/timer.h> has #include <lib/affine/ratio.h>.
      "//mk/ulib/affine",
    ]
  }
}

source_set("tests") {
  # TODO: testonly = true
  sources = [ "interrupts_test.cc" ]
  deps = [
    ":headers",
    "//mk/dev/interrupt",
    "//mk/lib/console",
    "//mk/lib/pow2_range_allocator",
    "//mk/lib/unittest",
  ]
}
