#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function HELP {
    echo "help:"
    echo "-6                  : x86-64"
    echo "-l                  : legacy mode build (386 emulated machine)"
    echo "-m <memory in MB>"
    echo "-s <number of cpus>"
    echo
    echo "-d <disk image>     : a virtio block device"
    echo "-g                  : with graphics"
    echo "-n                  : user mode networking, defaults to virtio-net-pci device"
    echo "-N <network driver> : specify network driver (virtio-net-pci, e1000e, etc)"
    echo "-t                  : use tap interface qemu0 for networking"
    echo "-k                  : use KVM"
    echo
    echo "-h for help"
    echo "all arguments after -- are passed to qemu directly"
    exit 1
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Note these match the defaults in [virtual device specs](/build/images/flash/BUILD.gn;l=517)
# and https://source.corp.google.com/fuchsia/build/sdk/virtual_device.gni
# (//src/developer/ffx/plugins/emulator/src/vdl_files.rs).This can be overriden by the emulator
# configs in the infra/recipe repo
# (https://fuchsia.googlesource.com/infra/recipes/+/refs/heads/main/recipe_modules/emu/api.py).
readonly MEMSIZE_DEFAULT=8192
readonly SMP_DEFAULT=4

# Host operating system. Will either be "Linux" or "Darwin" (macOS) on
# supported platforms.
HOST_OS=$(uname -s)
readonly HOST_OS

# Determine host architecture.
case "$(uname -m)" in
  aarch64*|arm64)
    readonly HOST_ARCH="arm64"
    ;;
  x86_64)
    readonly HOST_ARCH="x64"
    ;;
  *)
    echo "unknown host architecture: $(uname -m)"
    exit 1
    ;;
esac

DO_64BIT=0
DO_LEGACY=0
DO_GRAPHICS=0
DO_KVM=0
DO_DISK=0
DISK_IMAGE=""
DO_NET=0
DO_NET_TAP=0
QEMUDIR=
NETDEV=e1000e
MEMSIZE=$MEMSIZE_DEFAULT
SMP=1
SUDO=""
MAKE_VARS=""

while getopts 6d:gklm:nNq:s:th FLAG; do
    case $FLAG in
        6) DO_64BIT=1;;
        d) DO_DISK=1; DISK_IMAGE=$OPTARG;;
        g) DO_GRAPHICS=1;;
        k) DO_KVM=1;;
        l) DO_LEGACY=1;;
        m) MEMSIZE=$OPTARG;;
        n) DO_NET=1;;
        q) QEMUDIR=${OPTARG}/;;
        t) DO_NET_TAP=1;;
        N) NETDEV=$OPTARG;;
        s) SMP=$OPTARG;;
        h) HELP;;
        \?)
            echo unrecognized option $OPTARG
            HELP
    esac
done

shift $((OPTIND-1))

# by default use the qemu binary located in the fuchsia //prebuilt
# repo if we can find it, but allow -q to override it for people
# who want to use their own.
if [[ -z $QEMUDIR && -d "$DIR/../prebuilt/downloads/qemu/bin" ]]; then
    QEMUDIR="$DIR/../prebuilt/downloads/qemu/bin/"
fi

# pick the appropriate qemu and project
if (( $DO_64BIT )); then
    QEMU=${QEMUDIR}qemu-system-x86_64
    PROJECT="x64"
    CPU=max
    MACHINE=q35
elif (( $DO_LEGACY )); then
    QEMU=${QEMUDIR}qemu-system-i386
    PROJECT="pc-x86-legacy-test"
    CPU=486
    MACHINE=isapc
else
    QEMU=${QEMUDIR}qemu-system-i386
    PROJECT="pc-x86-test"
    CPU=max
    MACHINE=pc
fi

if (( $DO_LEGACY )); then
    if (( ! $MEMSIZE )); then
        MEMSIZE=4
    fi
else
    if (( ! $MEMSIZE )); then
        MEMSIZE=512
    fi
fi

ARGS=""
if (( $DO_KVM )); then
    ARGS+=" -enable-kvm -cpu host"
else
    ARGS+=" -cpu $CPU"
fi
ARGS+=" -m $MEMSIZE -smp $SMP -machine $MACHINE -kernel build-${PROJECT}/lk.elf"

ARGS+=" -device isa-debug-exit,iobase=0xf4,iosize=0x04"
# Override the SeaBIOS serial port to keep it from outputting
# a terminal reset on start.
ARGS+=" -fw_cfg name=etc/sercon-port,string=0"

if (( $DO_GRAPHICS )); then
    ARGS+=" -serial stdio -vga std"
    if (( ! $DO_LEGACY )); then
        # add a couple of virtio devices for good measure
        ARGS+=" -device virtio-keyboard-pci"
        ARGS+=" -device virtio-mouse-pci"
    fi
else
    ARGS+=" -nographic"
fi

if (( $DO_DISK )); then
    if (( ! $DO_LEGACY )); then
        ARGS+=" -drive if=none,file=${DISK_IMAGE},id=blk,discard=on -device virtio-blk-pci,drive=blk,discard=on"
    else
        ARGS+=" -hda ${DISK_IMAGE}"
    fi
fi
if (( $DO_NET )); then
    if (( ! $DO_LEGACY )); then
        if (( ! $DO_NET_TAP )); then
            ARGS+=" -netdev user,id=vmnic,hostname=qemu"
        else
            # quick note to enable tap interface
            # IFNAME=qemu0
            # BRIDGE=bridge0
            # sudo tunctl -u $(whoami) -t ${IFNAME}
            # sudo ifconfig ${IFNAME} up
            # sudo ip link set ${IFNAME} master ${BRIDGE}
            ARGS+=" -netdev tap,id=vmnic,ifname=qemu0,script=no,downscript=no"
            #SUDO="sudo"
        fi
        ARGS+=" -device $NETDEV,netdev=vmnic"
    else
        echo "implement legacy + network config"
        exit 1
    fi
else
    ARGS+=" -net none"
fi

$DIR/make-parallel $MAKE_VARS $PROJECT &&
echo $SUDO $QEMU $ARGS $@ &&
$SUDO $QEMU $ARGS $@

